server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sionicai?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update # 필요에 따라 create, update, validate 등으로 설정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # MySQL 전용 Dialect 설정
        format_sql: true
